FROM python:3
WORKDIR	/code
ENV FLASK_APP app.py
ENV FLASK_RUN_HOST 0.0.0.0
COPY requirements.txt requirements.txt
RUN apt-get update
RUN pip install -r requirements.txt
EXPOSE 8080
CMD ["flask", "run"]
